### ISSUE TITLE
Some fastdebug builds are actually release ones

### ISSUE THREAD

**Issue by genuss** [corretto/corretto-22#9]
Some nightly builds on https://downloads.corretto.aws are claimed having fastdebug debug level, although they are release one. For example, take the latest alpine x64 one: [2024-08-09](https://corretto.aws/nightly/2024/08/09/Corretto22/develop/87b5469814822b59a664bd1888676edd02323c70/fastdebug/alpine/x64/amazon-corretto-22.0.2.9.1-alpine-linux-x64.tar.gz), sha256 `4bb366c265e170f4b0b8ae287779abb0f559b45c8b5c62ec099f47d1f07f02b5`

The version string for it is:
```
$ java -version
openjdk version "22.0.2" 2024-08-09
OpenJDK Runtime Environment Corretto-22.0.2.9.1 (build 22.0.2+9-Nightly)
OpenJDK 64-Bit Server VM Corretto-22.0.2.9.1 (build 22.0.2+9-Nightly, mixed mode, sharing)
```

At the same time, mac os builds are indeed correct. For example the last one [2024-08-09](https://corretto.aws/nightly/2024/08/09/Corretto22/develop/87b5469814822b59a664bd1888676edd02323c70/fastdebug/macos/aarch64/amazon-corretto-22.0.2.9.1-macosx-aarch64-fastdebug.tar.gz):
```
~/Downloads/amazon-corretto-22.jdk/Contents/Home ❯ ./bin/java -version
openjdk version "22.0.2" 2024-08-09
OpenJDK Runtime Environment Corretto-22.0.2.9.1 (fastdebug build 22.0.2+9-Nightly)
OpenJDK 64-Bit Server VM Corretto-22.0.2.9.1 (fastdebug build 22.0.2+9-Nightly, mixed mode, sharing)
```

Could you look into it?

**Comment by shipilev** [comment]
Thanks for report! Confirmed, there is a configuration bug in our Alpine build pipelines. We are working on fixing this.

**Comment by rgithubli** [comment]
Hi, we've pushed the fixes for corretto-11 and above today. If you download those nightly builds generated after today, they should have right fastdebug builds.

corretto-8 fix is still pending. Leaving this issue open.

**Comment by genuss** [comment]
Hi, @rgithubli, thanks for the fix! I checked 23rd and 21st version. There are fastdebug build available indeed. Although, I was primarily interested in 22nd version, and I'm afraid you forgot to backport the fix in this repo.
I created a PR here https://github.com/corretto/corretto-22/pull/10. Could you look at it?

**Comment by rgithubli** [comment]
Yeah sorry. 23 is already in EA so I did not backport it into 22. Approved and merged your PR. Thanks. 

Side note: believe you're aware - 22 is non LTS and its EOL is coming soon in this Sept.

**Comment by genuss** [comment]
Thank you! All good, found the correct build in place.
